language: cpp


compiler:
  - clang
  - g++


before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
  - sudo apt-get install libboost-dev
  - sudo apt-get install g++-4.7
  - export CXX=g++-4.7


script:
  - make test
