language: cpp


compiler:
  - clang
  - g++


before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
  - sudo apt-get install libboost-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-4.7 ; fi
  - if [ "$CXX" = "g++" ]; then export CXX=g++-4.7 ; fi


script:
  - make test
